//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordene
    {
        public int Num_orden { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
        public int ID_arti { get; set; }
        public int Cantidad { get; set; }
        public int ID_med { get; set; }
        public decimal Unitario { get; set; }
        public decimal Total { get; set; }
        public int ID_prov { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Medida Medida { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
