//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedore()
        {
            this.Ordenes = new HashSet<Ordene>();
        }
    
        public int ID_prov { get; set; }
        public int ID_ID { get; set; }
        public string Nombre { get; set; }
        public int Estado { get; set; }
        public int ID_Direccion { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Identificacion Identificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordene> Ordenes { get; set; }
    }
}
